### ISSUE TITLE
Occasional failure somewhere in chatGPT file process.

### ISSUE THREAD

**Issue by Shyvadi** [Hacking-Notes/VulnScan#3]
Currently, example.ca would work most of the time however when new.example.ca is used it will fail (Although in some cases works fine)

When it fails, it will not create the chatGPT file successfully, either due to a bad response, invalid request, or improper file name.

**Comment by Shyvadi** [comment]
An example of a bad file name would be example.ca/213213123/page2.txt

where the original url was https://example.ca/213213123/page2

-

An example of a bad response could be if there is no response at all due to a bad API key or it is erroring and not properly showing. I suspect the problem lies here: 
![image](https://user-images.githubusercontent.com/22157510/226466667-8bb8ba7b-6512-43ef-b5e3-3bc3432523f6.png) The only error I can see is this: 
![image](https://user-images.githubusercontent.com/22157510/226467192-b3b64742-6231-462c-aa6f-3f3ae6cc3f0b.png)

**Comment by Hacking-Notes** [comment]
I think I have resolved the issue, let me know if it's working :)
